name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug Inputs
        run: |
          echo "GITHUB_ACTOR: ${{ github.92kareeem }}"
          echo "GITHUB_REPOSITORY: ${{ github.GitStats}}"

      - name: Generate Snake GIF
        uses: Platane/snk@v2.0.0
        with:
          github_user_name: ${{ github.92kareeem }}  # Using the actor who triggered the workflow
          svg_out_path: dist/snake.svg

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: snake-graph
          path: dist/snake.svg
